'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const loadTs = require('./load-ts.cjs');
const { lifetimeUsdFromRows, CostLedgerTotals } = loadTs('src/main/costLifetime.ts');
const row = (agentId, sessionId, usd) => ({ agentId, sessionId, usd });
const total = (rows, agent = 'a') => lifetimeUsdFromRows(rows).get(agent) ?? 0;

test('no reset uses the segment peak', () => assert.equal(total([row('a','s',1),row('a','s',5),row('a','s',9.25)]), 9.25));
test('one reset adds closed and open peaks', () => assert.equal(total([row('a','s',8),row('a','s',20),row('a','s',0),row('a','s',3)]), 23));
test('multiple resets accumulate', () => assert.equal(total([row('a','s',10),row('a','s',0),row('a','s',7),row('a','s',0),row('a','s',2)]), 19));
test('sub-dollar reset is not noise', () => assert.equal(total([row('a','s',0.92),row('a','s',0),row('a','s',0.4)]), 1.32));
test('same session id can contain reset', () => assert.equal(total([row('a','same',30),row('a','same',0),row('a','same',1)]), 31));
test('separate sessions sum', () => assert.equal(total([row('a','s1',4),row('a','s2',6)]), 10));
test('agents remain isolated', () => { const t=lifetimeUsdFromRows([row('a','s',3),row('b','s',7)]); assert.equal(t.get('a'),3); assert.equal(t.get('b'),7); });
test('equal values are not reset', () => assert.equal(total([row('a','s',2),row('a','s',2)]), 2));
test('epsilon noise is not reset', () => assert.equal(total([row('a','s',2),row('a','s',2-1e-10)]), 2));
test('invalid costs map to zero', () => assert.equal(total([row('a','s',Number.NaN),row('a','s',-1)]), 0));
test('empty input has no totals', () => assert.equal(lifetimeUsdFromRows([]).size, 0));
test('adapter warms from PostgreSQL result', async () => { const a=new CostLedgerTotals(async()=>new Map([['a',4]])); assert.equal(a.usdFor('a'),null); await a.refresh(); assert.equal(a.usdFor('a'),4); assert.equal(a.floorTotal(),4); });
