[package]
name = "md-web-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum-server = { workspace = true, optional = true }
dioxus.workspace = true
dioxus-router.workspace = true
futures-util = { workspace = true, optional = true }
md-web-contracts.workspace = true
md-web-services = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
serde_json.workspace = true
tokio = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server", "dep:axum-server", "dep:futures-util", "dep:md-web-services", "dep:rustls", "dep:tokio", "dep:uuid"]

[lints]
workspace = true
